name: Build and Push Docker Image

on:
  push:
    tags: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/christian2000/inkcut:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/christian2000/inkcut:buildcache
          cache-to: type=registry,ref=ghcr.io/christian2000/inkcut:buildcache,mode=max